### ISSUE TITLE
Improve directory structure

### ISSUE THREAD

**Issue by hatcat** [ISOCPP-2D/P0267_RefImpl#1]
The directory structure is designed around the prior assumption of a renderer baked into the implementation. This is no longer the case since r7.

The renderer and math classes that act as the default implementation should be moved out of the directory and into a new directory, named
P0267_RefImpl/P0267_RefImpl/win32.cairo
P0267_RefImpl/P0267_RefImpl/xlib.cairo
P0267_RefImpl/P0267_RefImpl/osx.coregraphics

Better names are of course acceptable, but the peering of the directories is the important part. Users should declare two include paths to their compilers:
P0267_RefImpl/P0267_RefImpl/P0267_RefImpl
P0267_RefImpl/P0267_RefImpl/*implementation*

I'm open to suggestions about how we manage the implementation binary.

**Comment by mikekazakov** [comment]
Can we consider splitting backends into parts?
Otherwise this will lead to significant code duplication inside backends.
For instance, in case of existing Cairo backend (and that's a naive approach with some code duplication between win32 and xlib):
common graphics part: ~3KSLoC;
win32 windowing: ~1.3KSLoC;
xlib windowing: ~1.3KSLoC.
Thus, a complete separation into two unrelated entities will end up in ~3KSLoC of redundant code per windowing system. Maintenance of such solution will be hard.
For CoreGraphics this proportion might be even bigger, like 3:1 for graphics and windowing parts.

So, IMHO it's reasonable to split backends into a graphics backend and a windowing backend, like this:
P0267_RefImpl/P0267_RefImpl/cairo
P0267_RefImpl/P0267_RefImpl/cairo/win32
P0267_RefImpl/P0267_RefImpl/cairo/xlib
P0267_RefImpl/P0267_RefImpl/cairo/...
P0267_RefImpl/P0267_RefImpl/coregraphics
P0267_RefImpl/P0267_RefImpl/coregraphics/cocoa
P0267_RefImpl/P0267_RefImpl/coregraphics/cocoa_touch
P0267_RefImpl/P0267_RefImpl/coregraphics/...
Where the majority of graphics-related source code is placed in the root directory of the backend (.../cairo and .../coregraphics) and windowing directories (win32, xlib, cocoa, etc) are relatively lightweight.

**Comment by DavidLudwig** [comment]
@hatcat , the directory structure you mentioned seems a bit redundant to me, in terms of how many times "R0267_RefImpl" is listed (in path-names).  Is this intentional?

In terms of naming implementations, any thoughts on what to name one, if it were cross-platform?  Say, for example, I wanted to write an implementation based on [LibSDL](https://libsdl.org) 2.x + Cairo?  "sdl2.cairo"?

**Comment by mikekazakov** [comment]
We discussed that IO2D paper/RefImpl has to support 3 kinds of “backend polymorphism”:
1) Configuration-time / development-time:
Specify a default backend of IO2D, which comes from <io2d.h>.
Then simply write graphics routines using default typenames from std::experimental::io2d.
This does not require any changes in client’s code.

2) Compile-time:
Add additional includes, like <io2d_direct2d_win32.h> and utilize this non-default backend via predefined namespaces, like:
```
namespace direct2d {
    using brush = basic_brush<direct2d_graphics_surfaces>;
}
```
or via custom using declarations, like:
```
namespace FooBar {
    using MyBrush = basic_brush<nvpath _graphics_surfaces>;
}
```
Then write graphics routines using these custom typenames instead of ones from std::experimental::io2d.

3) Run-time:
Add additional includes, same as in 2).
Write graphic routines templated with backend type, like this:
```
template<typename G, typename M>
void Draw(basic_image_surface<G> &surface, basic_point_2d<M> pos) {
    // do some stuff with “surface” on “pos” coordinates
}
```
Then add some high-level abstraction facility, which routes render requests into a proper specialization. This should allow two things:
  * Switch renders via a “combo-box” in run-time.
  * Display the same content drawn via different backends simultaneously.
I assume that such usage, albeit being possible, might be applied only to a narrow set of cases, mostly to research/testing/measurement, since writing such templated code is much harder than non-templated: - no code completion, - longer compilation times, - can’t hide internals in .cpp files.

(BTW, it would be great to cook the dictionary a bit: do we use the word “backend” or the word “renderer”? I would personally prefer the word “backend” since there’re quite a lot of routines not engaged in any sort of rendering)

Here’s my vision of how IO2D can support these requirements:

* Introduce and maintain a clear separation of IO2D API and its backends, which was discussed above.

* Each instance of [graphics backend]+[windowing backend] has to have two client-facing header files:
  1) io2d.h
This header provides a set of “using brush = basic_brush<..” carved in std::experimental::io2d namespace. Also, it pulls all necessary includes which are required to work with IO2D, so client code doesn’t need to include anything else.
	
  2) io2d_$GRAPHICS_$WINDOWING.h
For instance: io2d_cairo_win32.h, io2d_coregraphics_cocoa.h, io2d_direct2d_uwp.h etc. This header includes all other headers required to work with this backend and provides a custom namespace with “using…” declarations mentioned above. Also, it pulls all necessary includes which are required to work with IO2D, so client code doesn’t need to include anything else.
Thus, in directory structure this looks like (with examples for currently existing combinations):
P0267_RefImpl/P0267_RefImpl/cairo/win32/io2d.h
P0267_RefImpl/P0267_RefImpl/cairo/win32/io2d_cairo_win32.h
P0267_RefImpl/P0267_RefImpl/cairo/xlib/io2d.h
P0267_RefImpl/P0267_RefImpl/cairo/xlib/io2d_cairo_xlib.h
P0267_RefImpl/P0267_RefImpl/coregraphics/cocoa/io2d.h
P0267_RefImpl/P0267_RefImpl/coregraphics/cocoa/io2d_coregraphics_cocoa.h

* Usage on client side:
 #include <io2d.h> to use the default backend, chosen on configuration time. From a tooling perspective, this choice simply leads to the selection of the first search directory, in which a compiler can find this <io2d.h>.
 #include <io2d_cairo_win32.h> to manually pull some specific backend to use it.

* Tooling support. IO2D is not a header-only library, and even if it would be, there’re also dependencies of various backends to handle. I suggest we do aim at supporting CMake as a default build system, while it’s possible for an end-user to build the sources using other tools or manually. Thus, from a CMake perspective:
  - IO2D is a library, which is pulled by the client project, like this:
     target_link_libraries(rocks_in_space io2d)
  - IO2D library itself doesn’t contain any backends.
  - During configuration two values are passed to the CMake build script:
    - list of “enabled” backends.
      Each of backends is a library, which is added as a dependency to a project which uses IO2D.
      In practice each mentioning of a backend will pull appropriate sources like this:
add_subdirectory(P0267_RefImpl/P0267_RefImpl/cairo/win32)
    - default backend.
      This will set the first search path, where the <io2d.h> header could be found.
  For non-CMake build systems nothing stops from following the same logic.

* Known issues and limitations of this approach:
    - It will not allow usage of different windowing backends for the same graphics backend at the same time. For instance, you can’t say something like this:
#include <io2d_direct2d_win32.h>
#include <io2d_direct2d_uwp.h>
	and uses these backends interchangeably. I however assume there’s not much sense in doing this in the first place.

    - Shady interaction with future modules. It’s an open question whether depending on search paths order can play well with modules. I assume not, but modules themselves are full of questions now too.

    - Manual inclusion of different instances of io2d.h from different backends will lead to compilation errors and/or ODR violation.


Waiting for any feedback on this proposal. If there're no strong objections and/or other better solutions - I'll go ahead and perform these changes.

**Comment by hatcat** [comment]
This gets a nod from me.

Regarding the dictionary, backend is preferred to renderer for the simple reason that the backend consists of two things: the renderer AND the maths. BOTH of these will need to be pulled into separate implementation directory families. I suggest we follow the same process for each.

On a bikeshedding matter, there was considerable resistance to the name basic_* for the class templates. I think the way ahead would be to use the io2d namespace for the templates and the std (or client, or implementer) namespace for the specialisations, i.e.

```
namespace std::experimental::io2d
{
  template<GraphicsSurface>
  class brush {...};
}

namespace std::experimental
{
  using brush = io2d::brush<default_vendor_supplied_surface>;
}

namespace nvidia
{
  using brush = io2d::brush<nvidia_surface>;
}
```

I will open an issue in the paper repository to reflect this. There's something about inline namespaces, ADL and so on nagging in the back of my head though, so give me a day or so to mull it over.

**Comment by mikekazakov** [comment]
IMHO currently this is a minor stylistic annoyance and nothing more. An end-user will see only "brush" most of the time anyway.

**Comment by DavidLudwig** [comment]
One thought behind combining LibSDL and Cairo is that each excels at different things.  LibSDL is primarily a relatively-thin hardware abstraction library, one that doesn't have much in the way of graphics primitives, beyond a few basics, but is actively supported on a wide range of platforms, and has a ton of support for windowing, events, and graphics-context lifetimes.  Cairo looks to me like something that supports a much wider range of graphics operations (that LibSDL does not directly handle, nor do I suspect it ever will) such as drawing paths, gradients, text, etc.  The two seem complementary to me.  There's a bit of overlap, but the differences seem far greater-sized t me than the similarities.

I'll see if I can cook up at least one or two cross-platform samples, to try showing what might be possible.  I.e. more to come...

**Comment by mikekazakov** [comment]
One note regarding the new structure.
Since we're pulling at least two directories into search paths, it would be great to clearly separate internal stuff and external interface to prevent accidental inclusion of a wrong item.
STL packages usually put a prefix in front of a filename: MSVC uses the "x" prefix, Clang uses the "__" prefix. GCC tends to put internals into a separate directory, which stays out of search paths.
At this moment RefImpl partially follows MSVC's scheme - many internal files have the "x" prefix.
I'm ok with any of approaches a long as it is considered as the official way.
So, any thoughts here?

**Comment by hatcat** [comment]
x in front of internal filenames: if there are any WITHOUT the x then that is an earlier error.
The only exported filename should be io2d.h.

**Comment by mikekazakov** [comment]
Ok, I have a working Proof-of-Concept for a multiple backends configuration.

Here's a spoiler:
![screen shot 2018-04-07 at 11 36 18](https://user-images.githubusercontent.com/7439287/38451340-2fb26ab4-3a58-11e8-88e7-9ba4b700964d.png)
![screen shot 2018-04-07 at 11 36 38](https://user-images.githubusercontent.com/7439287/38451342-34c3785e-3a58-11e8-9404-a13fe960e703.png)

This example is pretty straightforward on the code side, there're only about 25 lines total:
```
#include <io2d_coregraphics_mac.h>
#include <io2d_cairo_xlib.h>

using namespace std;
using namespace std::experimental;
using namespace std::experimental::io2d;

template <typename G>
void Foo(G graphics_tag)
{
    auto display = basic_output_surface<G>{300, 300, format::argb32};
    display.draw_callback([](auto& surface) {
        surface.paint(basic_brush<G>{rgba_color::grey});
        surface.paint({ {{150.f, 150.f}, 90}, {{190.f, 190.f}, 0},
            {{0.0f, rgba_color::black}, {0.2f, rgba_color::dark_green}, {0.6f, rgba_color::green}, {1.0f, rgba_color::light_green}}});
    });
    display.begin_show();
}

int main(int argc, char **argv)
{
    argc < 2 ?
        Foo( _Cairo::_Cairo_graphics_surfaces<_Graphics_math_float_impl>{} ) :
        Foo( _CoreGraphics::_GS{} );
}
```

CMake config file looks pretty straightforward for this example too:
```
cmake_minimum_required(VERSION 3.0.0)
set(CMAKE_CXX_STANDARD 17)
project(multibackend_demo)
add_subdirectory(P0267_cg)
add_executable(multibackend_demo main.cpp)
target_link_libraries(multibackend_demo io2d)
```

As of configuration itself, I've introduced two CMake variables, which are supposed to be passed via command-line:
IO2D_DEFAULT - specifies the default backend for this configuration, possible values are CAIRO_WIN32, CAIRO_XLIB, COREGRAPHICS_MAC. 
IO2D_ENABLED - specifies a list of backends, which are includes into the build process. If this variable is not defined, IO2D_DEFAULT is used instead.

So it looks like these changes are ready to be merged into this RefImpl repository, probably in a separate branch.

**Comment by hatcat** [comment]
Looks good. How hard will this be for the maths part of the backend? I assume it will be quite trivial.

**Comment by mikekazakov** [comment]
Proper math integration has to be thought through.
At this moment it's easy to simply move _Graphics_math_float_impl into some directory, but more sophisticated implementation might require their own build process.
So, as a temporary solution, this will do. I suggest to rename this implementation into something like "_FloatMath" and put it into directory called "floatmath".

**Comment by mikekazakov** [comment]
In the meantime, Linux support was added in the CMake build script. So now Cairo/Xlib backend is now being tested on Linux via TravisCI.

**Comment by mikekazakov** [comment]
Well, I made the merge in the new "new_structure" branch.
Some things to note here:
* Old configuration scripts and Visual Studio projects were removed, as CMake now works as a single solution for every platform.
* Some basic BUILDING readme file was added. It describes the configuration process, available options and steps required for each backend. I do realise that this instruction is just a mere beginning, so any requests/recommendations/suggestions about expanding this file are welcome.
* We do need to hook CI on this repo. Guy, that's probably on your side, since AppVeyor seems to demand owning rights for a repo to include it. Config files are ready and running anyway, albeit in my fork.
* At this moment the current version of README file is outdated and we need to decide how to update it.
* Also I added another sample code: a miniature Life game.
* The tiny multibackend demo(showed above) can be added too, but it would require a special configuration, so it can't be included in a common list.
* We also need to decide something about branches management in this repo. Like master/development/stable for instance. I would like to continue my works on the CG backend (yes, it is not finished yet) inside this repo, to prevent another bifurcations, so some workflow scheme is required.

**Comment by hatcat** [comment]
Thanks for the merge Mike.

This looks like a number of additional issues Mike. Perhaps you could raise them separately and we'll address them individually. Be advised that Travis is switched on now.

The directory structure has been improved (in a different branch) so I'm going to close this issue.
